version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projeto-app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/bat_helpdesk
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: projeto-db
    environment:
      POSTGRES_DB: bat_helpdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
